{
 "title": "Current Temp",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current Temp",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "owm_current_temp" }
   ]
  },
  {
   "title": "Temp by time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "owm_current_temp", "legendFormat": "Current Temp" }
   ]
  },
  {
   "title": "Current Temp Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "owm_current_temp_max" }
   ]
  },
  {
   "title": "Current Temp Min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "owm_current_temp_min" }
   ]
  }
 ]
}